In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.DataFrame([[8,8,1],[7,9,1],[6,10,0],[5,5,0]], columns=['cgpa', 'profile_score', 'placed'])

In [3]:
df.head()

cgpa  profile_score  placed
0     8              8       1
1     7              9       1
2     6             10       0
3     5              5       0

In [4]:
import tensorflow
from tensorflow import keras
from tensorflow.keras import Sequential
from tensorflow.keras.layers import Dense

In [5]:
model = Sequential()

model.add(Dense(2,activation='sigmoid',input_dim=2))
model.add(Dense(1,activation='sigmoid'))

In [6]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 2)                 6         
                                                                 
 dense_1 (Dense)             (None, 1)                 3         
                                                                 
Total params: 9 (36.00 Byte)
Trainable params: 9 (36.00 Byte)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [7]:
model.get_weights()

[array([[1.1774472, 1.1060055],
        [0.8403481, 0.808462 ]], dtype=float32),
 array([0., 0.], dtype=float32),
 array([[-0.22288978],
        [ 0.06539094]], dtype=float32),
 array([0.], dtype=float32)]

In [8]:
new_weights = [np.array([[0.1, 0.1],
        [0.1, 0.1]], dtype=np.float32),
 np.array([0., 0.], dtype=np.float32),
 np.array([[ 0.1],
        [0.1]], dtype=np.float32),
 np.array([0.], dtype=np.float32)]

In [9]:
model.set_weights(new_weights)

In [10]:
model.get_weights()

[array([[0.1, 0.1],
        [0.1, 0.1]], dtype=float32),
 array([0., 0.], dtype=float32),
 array([[0.1],
        [0.1]], dtype=float32),
 array([0.], dtype=float32)]

In [13]:
optimizer = keras.optimizers.Adam(learning_rate=0.001)
model.compile(loss='binary_crossentropy',optimizer=optimizer)

In [15]:
model.fit(df.iloc[:,0:-1].values,df['placed'].values,epochs=50,verbose=1,batch_size=1)

Epoch 1/50
4/4 [==============================] - 0s 3ms/step - loss: 0.6943
Epoch 2/50
4/4 [==============================] - 0s 2ms/step - loss: 0.6942
Epoch 3/50
4/4 [==============================] - 0s 2ms/step - loss: 0.6938
Epoch 4/50
4/4 [==============================] - 0s 2ms/step - loss: 0.6938
Epoch 5/50
4/4 [==============================] - 0s 2ms/step - loss: 0.6939
Epoch 6/50
4/4 [==============================] - 0s 2ms/step - loss: 0.6938
Epoch 7/50
4/4 [==============================] - 0s 2ms/step - loss: 0.6937
Epoch 8/50
4/4 [==============================] - 0s 2ms/step - loss: 0.6937
Epoch 9/50
4/4 [==============================] - 0s 3ms/step - loss: 0.6937
Epoch 10/50
4/4 [==============================] - 0s 2ms/step - loss: 0.6937
Epoch 11/50
4/4 [==============================] - 0s 2ms/step - loss: 0.6939
Epoch 12/50
4/4 [==============================] - 0s 2ms/step - loss: 0.6936
Epoch 13/50
4/4 [==============================] - 0s 1ms/step - loss: 0.