In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.DataFrame([[8,8,4],[7,9,5],[6,10,6],[5,12,7]], columns=['cgpa', 'profile_score', 'lpa'])

In [5]:
df

cgpa  profile_score  lpa
0     8              8    4
1     7              9    5
2     6             10    6
3     5             12    7

In [6]:
import tensorflow
from tensorflow import keras
from tensorflow.keras import Sequential
from tensorflow.keras.layers import Dense

In [8]:
model = Sequential()

model.add(Dense(2,activation='linear',input_dim=2))
model.add(Dense(1,activation='linear'))

In [9]:
model.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 2)                 6         
                                                                 
 dense_1 (Dense)             (None, 1)                 3         
                                                                 
Total params: 9 (36.00 Byte)
Trainable params: 9 (36.00 Byte)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [12]:
model.get_weights()

[array([[-0.18010795,  0.7156743 ],
        [ 0.45189583, -0.37087286]], dtype=float32),
 array([0., 0.], dtype=float32),
 array([[ 0.04947364],
        [-0.23015285]], dtype=float32),
 array([0.], dtype=float32)]

In [14]:
new_weights = [np.array([[0.1, 0.1],
        [0.1, 0.1]], dtype=np.float32),
 np.array([0., 0.], dtype=np.float32),
 np.array([[ 0.1],
        [0.1]], dtype=np.float32),
 np.array([0.], dtype=np.float32)]

In [15]:
model.set_weights(new_weights)

In [16]:
model.get_weights()

[array([[0.1, 0.1],
        [0.1, 0.1]], dtype=float32),
 array([0., 0.], dtype=float32),
 array([[0.1],
        [0.1]], dtype=float32),
 array([0.], dtype=float32)]

In [18]:
optimizer = keras.optimizers.Adam(learning_rate=0.001)
model.compile(loss='mean_squared_error',optimizer=optimizer)

In [19]:
model.fit(df.iloc[:,0:-1].values,df['lpa'].values,epochs=75,verbose=1,batch_size=1)

Epoch 1/75
4/4 [==============================] - 0s 3ms/step - loss: 27.9165
Epoch 2/75
4/4 [==============================] - 0s 2ms/step - loss: 27.5745
Epoch 3/75
4/4 [==============================] - 0s 3ms/step - loss: 27.2679
Epoch 4/75
4/4 [==============================] - 0s 1ms/step - loss: 26.9091
Epoch 5/75
4/4 [==============================] - 0s 2ms/step - loss: 26.5707
Epoch 6/75
4/4 [==============================] - 0s 2ms/step - loss: 26.1993
Epoch 7/75
4/4 [==============================] - 0s 2ms/step - loss: 25.8369
Epoch 8/75
4/4 [==============================] - 0s 3ms/step - loss: 25.4854
Epoch 9/75
4/4 [==============================] - 0s 3ms/step - loss: 25.0750
Epoch 10/75
4/4 [==============================] - 0s 3ms/step - loss: 24.6635
Epoch 11/75
4/4 [==============================] - 0s 3ms/step - loss: 24.2466
Epoch 12/75
4/4 [==============================] - 0s 2ms/step - loss: 23.8189
Epoch 13/75
4/4 [==============================] - 0s 3ms/ste